const conversations = [
  {
    id: 1,
    title: "Di Toko / Supermarket",
    emoji: "🛒",
    situation: "Percakapan saat berbelanja di toko atau supermarket",
    dialogs: [
      { speaker: "A", en: "Excuse me, where can I find the bread?", id: "Permisi, di mana saya bisa menemukan roti?" },
      { speaker: "B", en: "It's in aisle three, next to the dairy products.", id: "Ada di lorong tiga, di sebelah produk susu." },
      { speaker: "A", en: "Thank you! How much is this bread?", id: "Terima kasih! Berapa harga roti ini?" },
      { speaker: "B", en: "It's two dollars and fifty cents.", id: "Harganya dua dolar lima puluh sen." },
      { speaker: "A", en: "Do you have any discounts today?", id: "Apakah ada diskon hari ini?" },
      { speaker: "B", en: "Yes, we have a ten percent discount on all bakery items.", id: "Ya, ada diskon sepuluh persen untuk semua produk roti." },
      { speaker: "A", en: "Great! I'll take two loaves then.", id: "Bagus! Saya akan ambil dua bungkus kalau begitu." },
      { speaker: "B", en: "Anything else I can help you with?", id: "Ada lagi yang bisa saya bantu?" },
      { speaker: "A", en: "No, that's all. Can I pay by card?", id: "Tidak, itu saja. Boleh saya bayar dengan kartu?" },
      { speaker: "B", en: "Of course! Please swipe your card here.", id: "Tentu saja! Silakan gesek kartu Anda di sini." },
    ]
  },
  {
    id: 2,
    title: "Di Restoran",
    emoji: "🍽️",
    situation: "Percakapan saat memesan makanan di restoran",
    dialogs: [
      { speaker: "A", en: "Good evening! Do you have a table for two?", id: "Selamat malam! Apakah ada meja untuk dua orang?" },
      { speaker: "B", en: "Yes, right this way please.", id: "Ya, silakan ikuti saya." },
      { speaker: "A", en: "Can I see the menu, please?", id: "Boleh saya lihat menunya?" },
      { speaker: "B", en: "Here you go. Today's special is grilled salmon.", id: "Ini dia. Menu spesial hari ini adalah salmon bakar." },
      { speaker: "A", en: "That sounds delicious! I'll have the grilled salmon.", id: "Kedengarannya lezat! Saya pesan salmon bakar." },
      { speaker: "B", en: "Great choice! What would you like to drink?", id: "Pilihan yang bagus! Anda mau minum apa?" },
      { speaker: "A", en: "I'll have a glass of orange juice, please.", id: "Saya minta segelas jus jeruk." },
      { speaker: "B", en: "Would you like anything for dessert?", id: "Apakah Anda mau memesan makanan penutup?" },
      { speaker: "A", en: "Yes, I'll have the chocolate cake.", id: "Ya, saya pesan kue coklat." },
      { speaker: "B", en: "I'll be right back with your order.", id: "Saya akan segera kembali dengan pesanan Anda." },
      { speaker: "A", en: "Excuse me, can I have the bill please?", id: "Permisi, boleh minta bon tagihan?" },
      { speaker: "B", en: "Of course! Here is your bill. Thank you for dining with us.", id: "Tentu! Ini tagihan Anda. Terima kasih sudah makan di sini." },
    ]
  },
  {
    id: 3,
    title: "Di Sekolah",
    emoji: "🏫",
    situation: "Percakapan di lingkungan sekolah antara siswa dan guru",
    dialogs: [
      { speaker: "A", en: "Good morning, sir. May I come in?", id: "Selamat pagi, Pak. Boleh saya masuk?" },
      { speaker: "B", en: "Good morning! Yes, please come in and take your seat.", id: "Selamat pagi! Ya, silakan masuk dan duduk." },
      { speaker: "A", en: "I'm sorry I'm late. The bus was delayed.", id: "Maaf saya terlambat. Busnya telat." },
      { speaker: "B", en: "It's okay, but try to be on time tomorrow.", id: "Tidak apa-apa, tapi coba tepat waktu besok ya." },
      { speaker: "A", en: "Yes, sir. What topic are we studying today?", id: "Baik, Pak. Hari ini kita belajar topik apa?" },
      { speaker: "B", en: "Today we are studying English grammar.", id: "Hari ini kita belajar tata bahasa Inggris." },
      { speaker: "A", en: "Excuse me, sir. I don't understand this part.", id: "Permisi, Pak. Saya tidak mengerti bagian ini." },
      { speaker: "B", en: "Sure, let me explain it again.", id: "Tentu, biar saya jelaskan lagi." },
      { speaker: "A", en: "Can I borrow your pen? Mine is out of ink.", id: "Boleh pinjam pulpen kamu? Punyaku habis tintanya." },
      { speaker: "B", en: "Sure, here you go. Don't forget to return it.", id: "Boleh, ini. Jangan lupa dikembalikan ya." },
    ]
  },
  {
    id: 4,
    title: "Di Dokter / Rumah Sakit",
    emoji: "🏥",
    situation: "Percakapan saat berkonsultasi dengan dokter",
    dialogs: [
      { speaker: "A", en: "Good morning, doctor. I'm not feeling well.", id: "Selamat pagi, Dokter. Saya tidak merasa baik." },
      { speaker: "B", en: "I'm sorry to hear that. What seems to be the problem?", id: "Sayang sekali. Apa yang kamu rasakan?" },
      { speaker: "A", en: "I have a headache and a sore throat.", id: "Saya sakit kepala dan tenggorokan saya sakit." },
      { speaker: "B", en: "How long have you had these symptoms?", id: "Sudah berapa lama kamu merasakan gejala ini?" },
      { speaker: "A", en: "Since yesterday morning.", id: "Sejak kemarin pagi." },
      { speaker: "B", en: "Do you have a fever?", id: "Apakah kamu demam?" },
      { speaker: "A", en: "Yes, my temperature was 38 degrees last night.", id: "Ya, suhu saya 38 derajat semalam." },
      { speaker: "B", en: "I see. Let me check your throat.", id: "Saya mengerti. Biar saya periksa tenggorokanmu." },
      { speaker: "A", en: "Is it serious, doctor?", id: "Apakah serius, Dokter?" },
      { speaker: "B", en: "No, it's just a common cold. I'll prescribe some medicine.", id: "Tidak, ini hanya flu biasa. Saya akan resepkan obat." },
      { speaker: "A", en: "Thank you, doctor. How many times a day should I take it?", id: "Terima kasih, Dokter. Berapa kali sehari saya minum obatnya?" },
      { speaker: "B", en: "Three times a day after meals. Rest well and drink plenty of water.", id: "Tiga kali sehari setelah makan. Istirahat yang cukup dan banyak minum air." },
    ]
  },
  {
    id: 5,
    title: "Di Transportasi",
    emoji: "🚌",
    situation: "Percakapan saat menggunakan transportasi umum",
    dialogs: [
      { speaker: "A", en: "Excuse me, does this bus go to the city center?", id: "Permisi, apakah bus ini menuju pusat kota?" },
      { speaker: "B", en: "Yes, it does. The city center is five stops from here.", id: "Ya, betul. Pusat kota ada lima pemberhentian dari sini." },
      { speaker: "A", en: "How much is the fare?", id: "Berapa ongkosnya?" },
      { speaker: "B", en: "It's two dollars for adults.", id: "Dua dolar untuk orang dewasa." },
      { speaker: "A", en: "Can I buy a ticket on the bus?", id: "Boleh beli tiket di dalam bus?" },
      { speaker: "B", en: "Yes, you can pay the driver directly.", id: "Ya, kamu bisa bayar langsung ke supir." },
      { speaker: "A", en: "How long will it take to get there?", id: "Berapa lama untuk sampai ke sana?" },
      { speaker: "B", en: "About fifteen minutes if there's no traffic.", id: "Sekitar lima belas menit kalau tidak macet." },
      { speaker: "A", en: "Could you let me know when we reach the city center?", id: "Bisakah kamu beritahu saya ketika sampai di pusat kota?" },
      { speaker: "B", en: "Sure, no problem!", id: "Tentu, tidak masalah!" },
    ]
  },
  {
    id: 6,
    title: "Di Hotel",
    emoji: "🏨",
    situation: "Percakapan saat check in dan menginap di hotel",
    dialogs: [
      { speaker: "A", en: "Good afternoon. I have a reservation under the name Bima.", id: "Selamat siang. Saya punya reservasi atas nama Bima." },
      { speaker: "B", en: "Welcome! Let me check your reservation.", id: "Selamat datang! Biar saya cek reservasi Anda." },
      { speaker: "A", en: "Here is my ID card.", id: "Ini kartu identitas saya." },
      { speaker: "B", en: "Thank you. You're booked for three nights in a deluxe room.", id: "Terima kasih. Anda memesan tiga malam di kamar deluxe." },
      { speaker: "A", en: "That's correct. Does the room have Wi-Fi?", id: "Betul. Apakah kamarnya ada Wi-Fi?" },
      { speaker: "B", en: "Yes, Wi-Fi is free for all guests.", id: "Ya, Wi-Fi gratis untuk semua tamu." },
      { speaker: "A", en: "What time is breakfast served?", id: "Jam berapa sarapan disajikan?" },
      { speaker: "B", en: "Breakfast is from seven to ten in the morning.", id: "Sarapan dari jam tujuh sampai sepuluh pagi." },
      { speaker: "A", en: "Can I request an extra pillow?", id: "Boleh saya minta bantal tambahan?" },
      { speaker: "B", en: "Of course! I'll have it sent to your room right away.", id: "Tentu! Akan segera saya kirimkan ke kamar Anda." },
    ]
  },
  {
    id: 7,
    title: "Di Bandara",
    emoji: "✈️",
    situation: "Percakapan saat check in dan di bandara",
    dialogs: [
      { speaker: "A", en: "Good morning. I'd like to check in for my flight to Bali.", id: "Selamat pagi. Saya ingin check in untuk penerbangan ke Bali." },
      { speaker: "B", en: "May I see your passport and ticket, please?", id: "Boleh saya lihat paspor dan tiket Anda?" },
      { speaker: "A", en: "Here you are.", id: "Ini dia." },
      { speaker: "B", en: "How many bags are you checking in?", id: "Berapa koper yang akan Anda masukkan ke bagasi?" },
      { speaker: "A", en: "Just one suitcase.", id: "Hanya satu koper." },
      { speaker: "B", en: "Please put your bag on the scale.", id: "Tolong taruh koper Anda di timbangan." },
      { speaker: "A", en: "Do I have a window seat?", id: "Apakah saya dapat kursi di dekat jendela?" },
      { speaker: "B", en: "Yes, you have seat 14A, which is a window seat.", id: "Ya, Anda dapat kursi 14A, kursi di dekat jendela." },
      { speaker: "A", en: "What time does boarding begin?", id: "Jam berapa proses boarding dimulai?" },
      { speaker: "B", en: "Boarding starts at 9:30 AM at gate B5.", id: "Boarding dimulai jam 9:30 pagi di gate B5." },
      { speaker: "A", en: "Thank you very much!", id: "Terima kasih banyak!" },
      { speaker: "B", en: "Have a pleasant flight!", id: "Selamat menikmati penerbangan!" },
    ]
  },
  {
    id: 8,
    title: "Wawancara Kerja",
    emoji: "💼",
    situation: "Percakapan saat wawancara pekerjaan",
    dialogs: [
      { speaker: "A", en: "Good morning. Please come in and have a seat.", id: "Selamat pagi. Silakan masuk dan duduk." },
      { speaker: "B", en: "Good morning. Thank you for having me.", id: "Selamat pagi. Terima kasih sudah mengundang saya." },
      { speaker: "A", en: "Can you tell me a little about yourself?", id: "Bisakah Anda ceritakan sedikit tentang diri Anda?" },
      { speaker: "B", en: "Sure. My name is Bima. I graduated from the University of Indonesia.", id: "Tentu. Nama saya Bima. Saya lulus dari Universitas Indonesia." },
      { speaker: "A", en: "What are your strengths?", id: "Apa kelebihan Anda?" },
      { speaker: "B", en: "I am a hard worker, quick learner, and good team player.", id: "Saya pekerja keras, cepat belajar, dan bisa bekerja sama dalam tim." },
      { speaker: "A", en: "Why do you want to work at our company?", id: "Mengapa Anda ingin bekerja di perusahaan kami?" },
      { speaker: "B", en: "I admire your company's values and I believe I can contribute greatly.", id: "Saya mengagumi nilai-nilai perusahaan Anda dan saya yakin bisa berkontribusi besar." },
      { speaker: "A", en: "Do you have any questions for us?", id: "Apakah Anda punya pertanyaan untuk kami?" },
      { speaker: "B", en: "Yes. What are the opportunities for career growth here?", id: "Ya. Apa saja peluang pengembangan karir di sini?" },
      { speaker: "A", en: "We will contact you within a week. Thank you for coming.", id: "Kami akan menghubungi Anda dalam seminggu. Terima kasih sudah datang." },
      { speaker: "B", en: "Thank you for the opportunity. I look forward to hearing from you.", id: "Terima kasih atas kesempatannya. Saya menantikan kabar dari Anda." },
    ]
  },
  {
    id: 9,
    title: "Percakapan Telepon",
    emoji: "📞",
    situation: "Percakapan saat berbicara melalui telepon",
    dialogs: [
      { speaker: "A", en: "Hello, this is Bima speaking. May I speak to Mr. John?", id: "Halo, ini Bima. Boleh saya bicara dengan Pak John?" },
      { speaker: "B", en: "I'm sorry, Mr. John is not available right now.", id: "Maaf, Pak John sedang tidak ada sekarang." },
      { speaker: "A", en: "When will he be available?", id: "Kapan beliau bisa dihubungi?" },
      { speaker: "B", en: "He should be back in about an hour.", id: "Beliau akan kembali sekitar satu jam lagi." },
      { speaker: "A", en: "Can I leave a message?", id: "Boleh saya tinggalkan pesan?" },
      { speaker: "B", en: "Of course. Go ahead.", id: "Tentu saja. Silakan." },
      { speaker: "A", en: "Please tell him to call me back at 0812-3456-7890.", id: "Tolong beritahu beliau untuk menghubungi saya di 0812-3456-7890." },
      { speaker: "B", en: "Sure, I'll pass on your message.", id: "Baik, saya akan sampaikan pesannya." },
      { speaker: "A", en: "Thank you very much. Goodbye.", id: "Terima kasih banyak. Selamat tinggal." },
      { speaker: "B", en: "You're welcome. Goodbye!", id: "Sama-sama. Selamat tinggal!" },
    ]
  },
  {
    id: 10,
    title: "Di Bank",
    emoji: "🏦",
    situation: "Percakapan saat melakukan transaksi di bank",
    dialogs: [
      { speaker: "A", en: "Good morning. I'd like to open a savings account.", id: "Selamat pagi. Saya ingin membuka rekening tabungan." },
      { speaker: "B", en: "Sure. Please fill out this form first.", id: "Tentu. Silakan isi formulir ini terlebih dahulu." },
      { speaker: "A", en: "What documents do I need?", id: "Dokumen apa saja yang saya butuhkan?" },
      { speaker: "B", en: "You'll need your ID card and a recent photo.", id: "Anda butuh kartu identitas dan foto terbaru." },
      { speaker: "A", en: "Is there a minimum deposit?", id: "Apakah ada setoran minimal?" },
      { speaker: "B", en: "Yes, the minimum deposit is one hundred thousand rupiah.", id: "Ya, setoran minimal adalah seratus ribu rupiah." },
      { speaker: "A", en: "I'd also like to withdraw some money.", id: "Saya juga ingin menarik uang." },
      { speaker: "B", en: "How much would you like to withdraw?", id: "Berapa yang ingin Anda tarik?" },
      { speaker: "A", en: "Five hundred thousand rupiah, please.", id: "Lima ratus ribu rupiah." },
      { speaker: "B", en: "Please sign here. Here is your money.", id: "Tolong tanda tangan di sini. Ini uang Anda." },
    ]
  },
  {
    id: 11,
    title: "Di Salon / Barbershop",
    emoji: "💇",
    situation: "Percakapan saat potong rambut di salon atau barbershop",
    dialogs: [
      { speaker: "A", en: "Hello! Do you have any appointments available today?", id: "Halo! Apakah ada jadwal kosong hari ini?" },
      { speaker: "B", en: "Yes, we have one slot open at three o'clock.", id: "Ya, ada satu slot kosong jam tiga." },
      { speaker: "A", en: "Perfect! I'd like a haircut please.", id: "Bagus! Saya mau potong rambut." },
      { speaker: "B", en: "What style would you like?", id: "Gaya apa yang Anda inginkan?" },
      { speaker: "A", en: "Just a trim please. Not too short.", id: "Sedikit dirapikan saja. Jangan terlalu pendek." },
      { speaker: "B", en: "Would you like me to wash your hair first?", id: "Mau saya cuci rambutnya dulu?" },
      { speaker: "A", en: "Yes please, that would be great.", id: "Ya tolong, itu bagus sekali." },
      { speaker: "B", en: "Is this length okay for you?", id: "Apakah panjang ini sudah sesuai?" },
      { speaker: "A", en: "A little shorter on the sides please.", id: "Sedikit lebih pendek di bagian samping." },
      { speaker: "B", en: "How's this? Is it to your liking?", id: "Bagaimana ini? Apakah sudah sesuai selera Anda?" },
      { speaker: "A", en: "It looks great! How much do I owe you?", id: "Kelihatannya bagus! Berapa yang harus saya bayar?" },
      { speaker: "B", en: "That'll be fifty thousand rupiah.", id: "Lima puluh ribu rupiah." },
    ]
  },
  {
    id: 12,
    title: "Mengajak Teman Jalan",
    emoji: "🎬",
    situation: "Percakapan saat mengajak teman untuk pergi bersama",
    dialogs: [
      { speaker: "A", en: "Hey! Are you free this weekend?", id: "Hei! Apakah kamu bebas akhir pekan ini?" },
      { speaker: "B", en: "Yes, I don't have any plans. Why?", id: "Ya, aku tidak ada rencana. Kenapa?" },
      { speaker: "A", en: "Would you like to go to the mall with me?", id: "Mau pergi ke mall bersamaku?" },
      { speaker: "B", en: "Sure, that sounds fun! What time?", id: "Boleh, kedengarannya seru! Jam berapa?" },
      { speaker: "A", en: "How about two o'clock in the afternoon?", id: "Bagaimana kalau jam dua siang?" },
      { speaker: "B", en: "That works for me. Should we watch a movie too?", id: "Itu cocok untukku. Apakah kita juga nonton film?" },
      { speaker: "A", en: "Great idea! There's a new action movie out.", id: "Ide bagus! Ada film aksi baru yang sedang tayang." },
      { speaker: "B", en: "I love action movies! Let's do it.", id: "Aku suka film aksi! Ayo kita lakukan." },
      { speaker: "A", en: "I'll buy the tickets online.", id: "Aku akan beli tiketnya secara online." },
      { speaker: "B", en: "Awesome! See you Saturday then.", id: "Sip! Sampai jumpa Sabtu kalau begitu." },
    ]
  },
  {
    id: 13,
    title: "Meminta Bantuan",
    emoji: "🆘",
    situation: "Percakapan saat membutuhkan bantuan dari orang lain",
    dialogs: [
      { speaker: "A", en: "Excuse me, could you help me please?", id: "Permisi, bisakah Anda membantu saya?" },
      { speaker: "B", en: "Of course! What do you need?", id: "Tentu saja! Apa yang Anda butuhkan?" },
      { speaker: "A", en: "I'm lost. Can you tell me how to get to the train station?", id: "Saya tersesat. Bisakah Anda beritahu cara ke stasiun kereta?" },
      { speaker: "B", en: "Sure! Go straight ahead and turn left at the traffic light.", id: "Tentu! Jalan lurus dan belok kiri di lampu merah." },
      { speaker: "A", en: "How far is it from here?", id: "Seberapa jauh dari sini?" },
      { speaker: "B", en: "It's about a ten-minute walk.", id: "Sekitar sepuluh menit jalan kaki." },
      { speaker: "A", en: "Is there a bus that goes there?", id: "Apakah ada bus yang ke sana?" },
      { speaker: "B", en: "Yes, bus number five stops right in front of the station.", id: "Ya, bus nomor lima berhenti tepat di depan stasiun." },
      { speaker: "A", en: "Thank you so much for your help!", id: "Terima kasih banyak atas bantuan Anda!" },
      { speaker: "B", en: "No problem at all. Have a good day!", id: "Sama sekali tidak masalah. Semoga harimu menyenangkan!" },
    ]
  },
  {
    id: 14,
    title: "Perkenalan Diri",
    emoji: "🤝",
    situation: "Percakapan saat berkenalan dengan orang baru",
    dialogs: [
      { speaker: "A", en: "Hi there! I don't think we've met before. I'm Bima.", id: "Hai! Sepertinya kita belum pernah bertemu. Saya Bima." },
      { speaker: "B", en: "Nice to meet you, Bima! I'm Sarah.", id: "Senang bertemu kamu, Bima! Saya Sarah." },
      { speaker: "A", en: "Where are you from, Sarah?", id: "Kamu dari mana, Sarah?" },
      { speaker: "B", en: "I'm from Bandung. And you?", id: "Saya dari Bandung. Kalau kamu?" },
      { speaker: "A", en: "I'm from Jakarta. What do you do for a living?", id: "Saya dari Jakarta. Apa pekerjaan kamu?" },
      { speaker: "B", en: "I'm a graphic designer. How about you?", id: "Saya desainer grafis. Kalau kamu?" },
      { speaker: "A", en: "I'm a student. I'm studying computer science.", id: "Saya mahasiswa. Saya belajar ilmu komputer." },
      { speaker: "B", en: "That's interesting! How long have you been in this city?", id: "Menarik sekali! Sudah berapa lama kamu di kota ini?" },
      { speaker: "A", en: "About two years. I really enjoy it here.", id: "Sekitar dua tahun. Saya sangat suka di sini." },
      { speaker: "B", en: "Me too! Maybe we can hang out sometime.", id: "Saya juga! Mungkin kita bisa jalan-jalan kapan-kapan." },
      { speaker: "A", en: "Sure! Here's my number. Let's keep in touch.", id: "Tentu! Ini nomor saya. Mari tetap berhubungan." },
      { speaker: "B", en: "Great! It was really nice meeting you.", id: "Bagus! Senang sekali bertemu kamu." },
    ]
  },
  {
    id: 15,
    title: "Di Acara / Pesta",
    emoji: "🎉",
    situation: "Percakapan saat menghadiri acara atau pesta",
    dialogs: [
      { speaker: "A", en: "Wow, this is a great party! Did you organize it?", id: "Wow, ini pesta yang luar biasa! Apakah kamu yang mengaturnya?" },
      { speaker: "B", en: "Yes! I'm glad you could make it.", id: "Ya! Senang kamu bisa datang." },
      { speaker: "A", en: "The decorations look amazing!", id: "Dekorasinya terlihat luar biasa!" },
      { speaker: "B", en: "Thank you! I worked really hard on them.", id: "Terima kasih! Saya bekerja keras untuk itu." },
      { speaker: "A", en: "What are we celebrating today?", id: "Apa yang kita rayakan hari ini?" },
      { speaker: "B", en: "It's my birthday! I just turned twenty-two.", id: "Ini ulang tahun saya! Saya baru saja berumur dua puluh dua." },
      { speaker: "A", en: "Happy birthday! I brought you a gift.", id: "Selamat ulang tahun! Saya membawakan kamu hadiah." },
      { speaker: "B", en: "Oh, you shouldn't have! Thank you so much.", id: "Oh, tidak perlu! Terima kasih banyak." },
      { speaker: "A", en: "Have you tried the food? It's delicious!", id: "Sudahkah kamu mencoba makanannya? Lezat sekali!" },
      { speaker: "B", en: "Yes! I made the cake myself.", id: "Ya! Saya membuat kuenya sendiri." },
      { speaker: "A", en: "Really? You're so talented!", id: "Sungguh? Kamu sangat berbakat!" },
      { speaker: "B", en: "Thank you! Please enjoy the party!", id: "Terima kasih! Silakan nikmati pestanya!" },
    ]
  },
];
