const stories = [
  {
    id: 1,
    title: 'The New Student',
    emoji: '🏫',
    level: 'Pemula',
    topic: 'Kehidupan sekolah',
    totalVocab: 24,
    chapters: [
      {
        num: 1,
        title: 'The First Day',
        id_title: 'Hari Pertama',
        scene: 'SMA Nusantara, Jakarta • Senin pagi',
        text: [
          { en: 'It was a bright Monday morning when [Bima|bima] arrived at his new school for the very first time.', id: 'Hari Senin pagi yang cerah saat Bima tiba di sekolah barunya untuk pertama kali.' },
          { en: 'He stood at the front gate, holding his [backpack|backpack] tightly, and looked around with wide eyes.', id: 'Dia berdiri di gerbang depan, memegang tasnya erat-erat, dan melihat sekeliling dengan mata lebar.' },
          { en: 'The school building was large and [impressive|impressive]. There were tall trees lining the pathway.', id: 'Gedung sekolah itu besar dan mengesankan. Ada pohon-pohon tinggi berjejer di sepanjang jalan.' },
          { en: '"I hope I can make new [friends|friends] here," Bima said quietly to himself.', id: '"Semoga saya bisa mendapat teman baru di sini," kata Bima pelan pada dirinya sendiri.' },
          { en: 'He took a deep breath and walked through the gate with a small [smile|smile] on his face.', id: 'Dia menarik napas dalam-dalam dan berjalan melewati gerbang dengan senyum kecil di wajahnya.' },
        ],
        words: { bima: 'tokoh utama cerita ini', backpack: 'tas ransel', impressive: 'mengesankan', friends: 'teman-teman', smile: 'senyum' },
        vocab: ['bright = cerah', 'stood = berdiri', 'tightly = erat-erat', 'lining = berjejer', 'quietly = pelan-pelan', 'breath = napas', 'gate = gerbang', 'wide = lebar'],
      },
      {
        num: 2,
        title: 'A Kind Classmate',
        id_title: 'Teman Sekelas yang Baik',
        scene: 'Kelas 10A • Jam pelajaran pertama',
        text: [
          { en: 'Bima [entered|entered] the classroom and looked for an empty seat.', id: 'Bima memasuki kelas dan mencari kursi kosong.' },
          { en: 'Most of the seats were already [occupied|occupied] by other students who were busy talking.', id: 'Sebagian besar kursi sudah terisi oleh siswa lain yang sedang mengobrol.' },
          { en: 'Suddenly, a girl with a bright smile [waved|waved] at him from the back of the room.', id: 'Tiba-tiba, seorang gadis dengan senyum cerah melambaikan tangan dari belakang ruangan.' },
          { en: '"Hey! You can sit here," she said in a [cheerful|cheerful] voice.', id: '"Hei! Kamu bisa duduk di sini," katanya dengan suara yang ceria.' },
          { en: 'Bima felt [relieved|relieved]. "Thank you. My name is Bima. I am new here."', id: 'Bima merasa lega. "Terima kasih. Nama saya Bima. Saya murid baru di sini."' },
        ],
        words: { entered: 'memasuki', occupied: 'sudah terisi', waved: 'melambaikan tangan', cheerful: 'ceria', relieved: 'lega' },
        vocab: ['empty = kosong', 'suddenly = tiba-tiba', 'back = belakang', 'nodded = mengangguk', 'welcome = selamat datang', 'introduced = memperkenalkan', 'next to = di sebelah', 'busy = sibuk'],
      },
      {
        num: 3,
        title: 'A New Beginning',
        id_title: 'Awal yang Baru',
        scene: 'Halaman sekolah • Jam istirahat',
        text: [
          { en: 'After school, Bima and Sarah sat together under a big tree in the [schoolyard|schoolyard].', id: 'Setelah sekolah, Bima dan Sarah duduk bersama di bawah pohon besar di halaman sekolah.' },
          { en: 'They talked and laughed about many things. Bima could not believe how quickly the day had passed.', id: 'Mereka mengobrol dan tertawa tentang banyak hal. Bima tidak percaya betapa cepatnya hari berlalu.' },
          { en: '"[Honestly|honestly], I was very [nervous|nervous] this morning. I thought nobody would talk to me."', id: '"Jujurnya, saya sangat gugup pagi ini. Saya pikir tidak ada yang akan mengajak bicara saya."' },
          { en: 'Sarah laughed [kindly|kindly]. "Everyone feels that way on the first day. But now you have a friend!"', id: 'Sarah tertawa dengan baik hati. "Semua orang merasa begitu di hari pertama. Tapi sekarang kamu punya teman!"' },
          { en: 'Bima smiled back. He knew this school was going to be a [wonderful|wonderful] new chapter in his life.', id: 'Bima tersenyum balik. Dia tahu sekolah ini akan menjadi babak baru yang luar biasa dalam hidupnya.' },
        ],
        words: { schoolyard: 'halaman sekolah', honestly: 'jujurnya', nervous: 'gugup', kindly: 'dengan baik hati', wonderful: 'luar biasa' },
        vocab: ['together = bersama', 'quickly = dengan cepat', 'passed = berlalu', 'nobody = tidak ada', 'warmly = dengan hangat', 'truly = sungguh-sungguh', 'chapter = babak baru', 'laughed = tertawa'],
      },
    ],
  },
  {
    id: 2,
    title: 'A Day at the Market',
    emoji: '🛒',
    level: 'Pemula',
    topic: 'Belanja di pasar',
    totalVocab: 24,
    chapters: [
      {
        num: 1,
        title: 'Early Morning',
        id_title: 'Pagi-pagi Sekali',
        scene: 'Pasar Tradisional • Pukul 6 pagi',
        text: [
          { en: 'The sun had just risen when Dina and her mother [headed|headed] to the traditional market.', id: 'Matahari baru saja terbit ketika Dina dan ibunya berangkat ke pasar tradisional.' },
          { en: 'The market was already [crowded|crowded] with people carrying baskets and bags.', id: 'Pasar sudah ramai dengan orang-orang yang membawa keranjang dan tas.' },
          { en: 'The smell of fresh vegetables and [spices|spices] filled the air.', id: 'Aroma sayuran segar dan rempah-rempah memenuhi udara.' },
          { en: '"What do we need to [buy|buy] today, Mom?" Dina asked with a [curious|curious] look.', id: '"Apa yang perlu kita beli hari ini, Bu?" tanya Dina dengan tampang penasaran.' },
          { en: '"We need vegetables, fruit, fish, and some [ingredients|ingredients] for tonight\'s dinner," her mother replied.', id: '"Kita perlu sayuran, buah, ikan, dan beberapa bahan untuk makan malam nanti," jawab ibunya.' },
        ],
        words: { headed: 'berangkat / menuju', crowded: 'ramai / padat', spices: 'rempah-rempah', buy: 'membeli', curious: 'penasaran', ingredients: 'bahan-bahan masakan' },
        vocab: ['risen = terbit', 'traditional = tradisional', 'carrying = membawa', 'baskets = keranjang', 'smell = aroma', 'fresh = segar', 'filled = memenuhi', 'replied = menjawab'],
      },
      {
        num: 2,
        title: 'Bargaining',
        id_title: 'Tawar-menawar',
        scene: 'Lapak sayuran • Bagian dalam pasar',
        text: [
          { en: 'Dina\'s mother stopped at a vegetable stall and picked up a bunch of [spinach|spinach].', id: 'Ibu Dina berhenti di lapak sayuran dan mengambil seikat bayam.' },
          { en: '"How much is this?" she asked the [vendor|vendor], a friendly old woman.', id: '"Berapa harganya?" tanya ibu kepada pedagang, seorang wanita tua yang ramah.' },
          { en: '"Five thousand rupiah," the woman [answered|answered].', id: '"Lima ribu rupiah," jawab wanita itu.' },
          { en: 'Dina\'s mother smiled. "Can you give me a [discount|discount]? I buy here every week."', id: 'Ibu Dina tersenyum. "Boleh dikurangi sedikit? Saya belanja di sini setiap minggu."' },
          { en: 'The old woman [agreed|agreed] and gave them the spinach for four thousand. Everyone was [happy|happy].', id: 'Wanita tua itu setuju dan memberi mereka bayam seharga empat ribu. Semua senang.' },
        ],
        words: { spinach: 'bayam', vendor: 'pedagang', answered: 'menjawab', discount: 'diskon / potongan harga', agreed: 'setuju', happy: 'senang / bahagia' },
        vocab: ['stopped = berhenti', 'stall = lapak / kios', 'picked up = mengambil', 'bunch = seikat', 'friendly = ramah', 'every week = setiap minggu', 'gave = memberikan', 'four thousand = empat ribu'],
      },
      {
        num: 3,
        title: 'Going Home',
        id_title: 'Pulang ke Rumah',
        scene: 'Perjalanan pulang • Pukul 8 pagi',
        text: [
          { en: 'Their [bags|bags] were now full of fresh vegetables, fruit, and fish.', id: 'Tas-tas mereka kini penuh dengan sayuran segar, buah-buahan, dan ikan.' },
          { en: 'Dina helped her mother [carry|carry] the heavy bags on the way home.', id: 'Dina membantu ibunya membawa tas-tas berat dalam perjalanan pulang.' },
          { en: '"Mom, I [enjoyed|enjoyed] going to the market today," Dina said with a big smile.', id: '"Bu, saya senang pergi ke pasar hari ini," kata Dina dengan senyum lebar.' },
          { en: '"That is because you were a great [helper|helper]!" her mother said proudly.', id: '"Itu karena kamu adalah pembantu yang hebat!" kata ibunya dengan bangga.' },
          { en: 'Dina felt [proud|proud]. She could not wait to help cook dinner with all the fresh ingredients they bought.', id: 'Dina merasa bangga. Dia tidak sabar untuk membantu memasak makan malam dengan semua bahan segar yang mereka beli.' },
        ],
        words: { bags: 'tas-tas', carry: 'membawa / mengangkat', enjoyed: 'menikmati', helper: 'pembantu', proud: 'bangga' },
        vocab: ['full = penuh', 'heavy = berat', 'way = jalan / perjalanan', 'great = hebat', 'proudly = dengan bangga', 'could not wait = tidak sabar', 'cook = memasak', 'bought = membeli (lampau)'],
      },
    ],
  },
  {
    id: 3,
    title: 'The Lost Traveler',
    emoji: '✈️',
    level: 'Menengah',
    topic: 'Wisatawan yang tersesat',
    totalVocab: 24,
    chapters: [
      {
        num: 1,
        title: 'A Strange City',
        id_title: 'Kota yang Asing',
        scene: 'Kota baru yang tidak dikenal • Sore hari',
        text: [
          { en: 'Alex had just [landed|landed] in a new city after a long flight.', id: 'Alex baru saja mendarat di kota baru setelah penerbangan panjang.' },
          { en: 'He looked at his map but felt completely [confused|confused]. The street names were different from what he expected.', id: 'Dia melihat petanya tetapi merasa benar-benar bingung. Nama-nama jalan berbeda dari yang dia perkirakan.' },
          { en: '"I think I am [lost|lost]," he said to himself, looking around at the busy streets.', id: '"Sepertinya saya tersesat," katanya pada diri sendiri, melihat sekeliling jalan yang ramai.' },
          { en: 'He [approached|approached] a local man sitting on a bench nearby.', id: 'Dia mendekati seorang pria lokal yang duduk di bangku di dekatnya.' },
          { en: '"Excuse me, could you help me? I am trying to find my [hotel|hotel]," Alex said politely.', id: '"Permisi, bisakah kamu membantu saya? Saya sedang mencari hotel saya," kata Alex dengan sopan.' },
        ],
        words: { landed: 'mendarat', confused: 'bingung', lost: 'tersesat', approached: 'mendekati', hotel: 'hotel' },
        vocab: ['flight = penerbangan', 'street = jalan', 'expected = diperkirakan', 'busy = ramai', 'nearby = di dekat sini', 'politely = dengan sopan', 'trying = sedang mencoba', 'find = menemukan'],
      },
      {
        num: 2,
        title: 'Asking for Help',
        id_title: 'Meminta Bantuan',
        scene: 'Bangku taman • Di tepi jalan',
        text: [
          { en: 'The man smiled warmly and said, "Of course! Which hotel are you looking for?"', id: 'Pria itu tersenyum hangat dan berkata, "Tentu saja! Hotel mana yang kamu cari?"' },
          { en: 'Alex showed him the [address|address] on his phone. "It\'s called the Grand Palace Hotel."', id: 'Alex menunjukkan alamatnya di ponsel. "Namanya Grand Palace Hotel."' },
          { en: '"Ah, I know that place! Go straight ahead, then turn [left|left] at the traffic light," the man explained.', id: '"Ah, saya tahu tempat itu! Jalan lurus ke depan, lalu belok kiri di lampu merah," jelas pria itu.' },
          { en: '"After that, you will see a big fountain. The hotel is right [opposite|opposite] it," he added.', id: '"Setelah itu, kamu akan melihat air mancur besar. Hotel itu tepat di seberangnya," tambahnya.' },
          { en: 'Alex [thanked|thanked] the man and followed his [directions|directions] carefully.', id: 'Alex berterima kasih kepada pria itu dan mengikuti petunjuk arahnya dengan cermat.' },
        ],
        words: { address: 'alamat', left: 'kiri', opposite: 'di seberang', thanked: 'berterima kasih', directions: 'petunjuk arah' },
        vocab: ['warmly = dengan hangat', 'showed = menunjukkan', 'straight = lurus', 'traffic light = lampu merah', 'fountain = air mancur', 'added = menambahkan', 'followed = mengikuti', 'carefully = dengan cermat'],
      },
      {
        num: 3,
        title: 'Finally Found',
        id_title: 'Akhirnya Ditemukan',
        scene: 'Grand Palace Hotel • Menjelang malam',
        text: [
          { en: 'After walking for about ten minutes, Alex finally [spotted|spotted] the big fountain.', id: 'Setelah berjalan sekitar sepuluh menit, Alex akhirnya melihat air mancur besar itu.' },
          { en: 'And there, right across the fountain, was the Grand Palace Hotel, tall and [magnificent|magnificent].', id: 'Dan di sana, tepat di seberang air mancur, adalah Grand Palace Hotel yang tinggi dan megah.' },
          { en: 'Alex felt a huge sense of [relief|relief] wash over him. He walked into the hotel lobby with a big smile.', id: 'Alex merasakan rasa lega yang besar. Dia masuk ke lobi hotel dengan senyum lebar.' },
          { en: '"Welcome, sir. Do you have a [reservation|reservation]?" the receptionist asked kindly.', id: '"Selamat datang, Pak. Apakah Bapak memiliki reservasi?" tanya resepsionis dengan ramah.' },
          { en: '"Yes, I do. And I must say, your city is quite an [adventure|adventure]!" Alex said with a laugh.', id: '"Ya, saya ada. Dan saya harus bilang, kota Anda adalah petualangan yang luar biasa!" kata Alex sambil tertawa.' },
        ],
        words: { spotted: 'melihat / menemukan', magnificent: 'megah / indah', relief: 'kelegaan', reservation: 'reservasi / pemesanan', adventure: 'petualangan' },
        vocab: ['finally = akhirnya', 'across = di seberang', 'huge = sangat besar', 'sense = rasa', 'lobby = lobi', 'receptionist = resepsionis', 'quite = cukup', 'laugh = tertawa'],
      },
    ],
  },
  {
    id: 4,
    title: 'The Job Interview',
    emoji: '💼',
    level: 'Menengah',
    topic: 'Wawancara kerja',
    totalVocab: 24,
    chapters: [
      {
        num: 1,
        title: 'The Big Day',
        id_title: 'Hari yang Penting',
        scene: 'Kantor perusahaan besar • Pagi hari',
        text: [
          { en: 'Rafi had been [preparing|preparing] for this job interview for two weeks.', id: 'Rafi sudah mempersiapkan wawancara kerja ini selama dua minggu.' },
          { en: 'He wore his best suit and checked his [appearance|appearance] one last time in the mirror.', id: 'Dia memakai jas terbaiknya dan memeriksa penampilannya sekali lagi di depan cermin.' },
          { en: '"You can do this, Rafi," he told himself, trying to stay [confident|confident].', id: '"Kamu bisa melakukannya, Rafi," katanya pada diri sendiri, berusaha tetap percaya diri.' },
          { en: 'He arrived at the office ten minutes early, showing that he was [punctual|punctual] and serious.', id: 'Dia tiba di kantor sepuluh menit lebih awal, menunjukkan bahwa dia tepat waktu dan serius.' },
          { en: 'The [receptionist|receptionist] greeted him and asked him to wait in the lobby.', id: 'Resepsionis menyambutnya dan memintanya menunggu di lobi.' },
        ],
        words: { preparing: 'mempersiapkan', appearance: 'penampilan', confident: 'percaya diri', punctual: 'tepat waktu', receptionist: 'resepsionis' },
        vocab: ['interview = wawancara', 'suit = jas', 'checked = memeriksa', 'mirror = cermin', 'early = lebih awal', 'showing = menunjukkan', 'greeted = menyambut', 'lobby = lobi'],
      },
      {
        num: 2,
        title: 'Inside the Room',
        id_title: 'Di Dalam Ruangan',
        scene: 'Ruang wawancara • Lantai 5',
        text: [
          { en: 'A tall man in a blue suit [welcomed|welcomed] Rafi into the interview room.', id: 'Seorang pria tinggi berbaju jas biru menyambut Rafi ke ruang wawancara.' },
          { en: '"Please have a seat. My name is Mr. Hendra, the [manager|manager] of this department," he said.', id: '"Silakan duduk. Nama saya Pak Hendra, manajer departemen ini," katanya.' },
          { en: '"Tell me about yourself and why you want to [join|join] our company," Mr. Hendra began.', id: '"Ceritakan tentang diri Anda dan mengapa Anda ingin bergabung dengan perusahaan kami," Pak Hendra memulai.' },
          { en: 'Rafi took a deep breath and answered [clearly|clearly] and with confidence.', id: 'Rafi menarik napas dalam dan menjawab dengan jelas dan penuh kepercayaan diri.' },
          { en: '"I have three years of [experience|experience] in this field and I believe I can contribute greatly to your team."', id: '"Saya memiliki tiga tahun pengalaman di bidang ini dan saya yakin bisa berkontribusi besar untuk tim Anda."' },
        ],
        words: { welcomed: 'menyambut', manager: 'manajer', join: 'bergabung', clearly: 'dengan jelas', experience: 'pengalaman' },
        vocab: ['tall = tinggi', 'department = departemen', 'began = memulai', 'confidence = kepercayaan diri', 'believe = percaya', 'contribute = berkontribusi', 'field = bidang', 'greatly = secara besar'],
      },
      {
        num: 3,
        title: 'The Good News',
        id_title: 'Kabar Baik',
        scene: 'Tiga hari kemudian • Di rumah Rafi',
        text: [
          { en: 'Three days after the interview, Rafi received an [email|email] from the company.', id: 'Tiga hari setelah wawancara, Rafi menerima email dari perusahaan.' },
          { en: 'His hands were [shaking|shaking] slightly as he opened it.', id: 'Tangannya sedikit gemetar saat membukanya.' },
          { en: '"Dear Mr. Rafi, we are pleased to inform you that you have been [selected|selected] for the position."', id: '"Yth. Bapak Rafi, kami dengan senang hati memberitahukan bahwa Anda telah dipilih untuk posisi tersebut."' },
          { en: 'Rafi could not believe it. He jumped up and [shouted|shouted] with joy.', id: 'Rafi tidak bisa percaya. Dia melompat dan berteriak kegirangan.' },
          { en: 'All his hard work and [preparation|preparation] had finally paid off. His dream had come true.', id: 'Semua kerja keras dan persiapannya akhirnya membuahkan hasil. Mimpinya menjadi kenyataan.' },
        ],
        words: { email: 'surel / email', shaking: 'gemetar', selected: 'dipilih / terpilih', shouted: 'berteriak', preparation: 'persiapan' },
        vocab: ['received = menerima', 'slightly = sedikit', 'pleased = dengan senang hati', 'inform = memberitahukan', 'position = posisi', 'jumped = melompat', 'joy = kegembiraan', 'paid off = membuahkan hasil'],
      },
    ],
  },
  {
    id: 5,
    title: 'The Rainy Adventure',
    emoji: '🌧️',
    level: 'Menengah',
    topic: 'Petualangan saat hujan',
    totalVocab: 24,
    chapters: [
      {
        num: 1,
        title: 'Caught in the Rain',
        id_title: 'Kehujanan',
        scene: 'Jalanan kota • Sore hari',
        text: [
          { en: 'Maya was walking home from school when the sky suddenly turned dark and it began to [pour|pour].', id: 'Maya sedang berjalan pulang dari sekolah ketika langit tiba-tiba menjadi gelap dan hujan mulai turun dengan deras.' },
          { en: 'She had not brought an [umbrella|umbrella] and was quickly getting soaked.', id: 'Dia tidak membawa payung dan cepat-cepat menjadi basah kuyup.' },
          { en: 'Maya ran to the nearest [shelter|shelter], a small warung by the roadside.', id: 'Maya berlari ke tempat berlindung terdekat, sebuah warung kecil di pinggir jalan.' },
          { en: 'Inside, she found two other students who were also [escaping|escaping] the rain.', id: 'Di dalam, dia menemukan dua siswa lain yang juga berlindung dari hujan.' },
          { en: '"Looks like we are all [stuck|stuck] here for a while," one of them said with a laugh.', id: '"Sepertinya kita semua terjebak di sini sebentar," kata salah satu dari mereka sambil tertawa.' },
        ],
        words: { pour: 'hujan deras', umbrella: 'payung', shelter: 'tempat berlindung', escaping: 'berlindung dari', stuck: 'terjebak' },
        vocab: ['walking = berjalan', 'suddenly = tiba-tiba', 'turned dark = menjadi gelap', 'soaked = basah kuyup', 'nearest = terdekat', 'roadside = pinggir jalan', 'found = menemukan', 'while = sebentar'],
      },
      {
        num: 2,
        title: 'New Friends',
        id_title: 'Teman Baru',
        scene: 'Warung pinggir jalan • Masih hujan',
        text: [
          { en: 'The three students [introduced|introduced] themselves. The other two were Andi and Lisa.', id: 'Ketiga siswa itu saling memperkenalkan diri. Dua lainnya adalah Andi dan Lisa.' },
          { en: 'The warung owner, a kind old man, [offered|offered] them hot tea while they waited.', id: 'Pemilik warung, seorang pria tua yang baik, menawarkan mereka teh panas sambil menunggu.' },
          { en: '"This is so [cozy|cozy]," Lisa said, wrapping her hands around the warm cup.', id: '"Ini sangat nyaman," kata Lisa, melingkarkan tangannya di sekitar cangkir yang hangat.' },
          { en: 'They talked and [shared|shared] stories about their schools, hobbies, and favorite foods.', id: 'Mereka mengobrol dan berbagi cerita tentang sekolah, hobi, dan makanan favorit mereka.' },
          { en: 'Maya [realized|realized] that being caught in the rain was actually turning into a great experience.', id: 'Maya menyadari bahwa kehujanan ini sebenarnya berubah menjadi pengalaman yang menyenangkan.' },
        ],
        words: { introduced: 'memperkenalkan diri', offered: 'menawarkan', cozy: 'nyaman / hangat', shared: 'berbagi', realized: 'menyadari' },
        vocab: ['owner = pemilik', 'hot = panas', 'waited = menunggu', 'wrapping = melingkarkan', 'warm = hangat', 'hobbies = hobi', 'actually = sebenarnya', 'turning into = berubah menjadi'],
      },
      {
        num: 3,
        title: 'After the Rain',
        id_title: 'Setelah Hujan',
        scene: 'Jalanan setelah hujan • Sore menjelang malam',
        text: [
          { en: 'After about an hour, the rain finally [stopped|stopped] and the sky became clear again.', id: 'Setelah sekitar satu jam, hujan akhirnya berhenti dan langit kembali cerah.' },
          { en: 'A beautiful [rainbow|rainbow] appeared across the sky, making everyone smile.', id: 'Pelangi indah muncul melintasi langit, membuat semua orang tersenyum.' },
          { en: 'Maya, Andi, and Lisa exchanged phone numbers before going their [separate|separate] ways.', id: 'Maya, Andi, dan Lisa bertukar nomor telepon sebelum pergi ke jalan masing-masing.' },
          { en: '"This was the best [unexpected|unexpected] adventure I have ever had!" Maya said happily.', id: '"Ini adalah petualangan tak terduga terbaik yang pernah saya alami!" kata Maya dengan gembira.' },
          { en: 'She walked home with wet shoes but a heart full of [gratitude|gratitude] for the new friends she had made.', id: 'Dia berjalan pulang dengan sepatu basah tetapi hati penuh rasa syukur atas teman-teman baru yang didapatnya.' },
        ],
        words: { stopped: 'berhenti', rainbow: 'pelangi', separate: 'masing-masing', unexpected: 'tak terduga', gratitude: 'rasa syukur' },
        vocab: ['finally = akhirnya', 'clear = cerah', 'appeared = muncul', 'across = melintasi', 'exchanged = bertukar', 'going = pergi', 'wet = basah', 'heart = hati / perasaan'],
      },
    ],
  },
];
